library(shinydashboard)
library(shiny)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(shinydashboardPlus)
library(hrbrthemes)
library(shinyWidgets)
library(here)
library(DT)
library(gridExtra)

load("data/FinalTotalMedals.Rdata")
load("data/FinalYearWiseMedals.Rdata")
load("data/height_age_weight.Rdata")
load("data/olympics.Rdata")
load("data/olympics_countries.Rdata")
load("data/countries.Rdata")
load("data/counts.Rdata")

source("plots/plot2_gold.R", local = T)
source("plots/plot2_silver.R", local = T)
source("plots/plot2_bronze.R", local = T)
source("plots/plot2_total.R", local = T)
source("plots/plot_host.R", local = T)
source("plots/plot_height.R", local = T)
source("plots/plot_Weight.R", local = T)
source("plots/plot_age.R", local = T)
source("plots/plot_alcohol.R", local = T)
source("plots/plot_beer.R", local = T)
source("plots/plot_indep.R", local = T)
source("plots/plot_lifeExp.R", local = T)
source("plots/plot_unemployment.R", local = T)
source("plots/plot_suicide.R", local = T)
source("plots/plot_pop.R", local = T)
source("plots/plot_lit.R", local = T)
source("plots/plot_forest.R", local = T)